// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8udR6zu0gCBtjGk95HE055sSCApktzRs',
    appId: '1:1001638282578:web:c99717769dbf74a444268b',
    messagingSenderId: '1001638282578',
    projectId: 'flutter-ecommerce-7407b',
    authDomain: 'flutter-ecommerce-7407b.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-7407b.appspot.com',
    measurementId: 'G-7L8WNYS0VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndFe2pksosBbMsfRBV7PohXeoHntvnvE',
    appId: '1:1001638282578:android:b409a16fcf8426f344268b',
    messagingSenderId: '1001638282578',
    projectId: 'flutter-ecommerce-7407b',
    storageBucket: 'flutter-ecommerce-7407b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeW1mqpUbMFX1OdFXKauPR1SgxxcJw8Yg',
    appId: '1:1001638282578:ios:ba43ef0a5948fb7944268b',
    messagingSenderId: '1001638282578',
    projectId: 'flutter-ecommerce-7407b',
    storageBucket: 'flutter-ecommerce-7407b.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeW1mqpUbMFX1OdFXKauPR1SgxxcJw8Yg',
    appId: '1:1001638282578:ios:ba43ef0a5948fb7944268b',
    messagingSenderId: '1001638282578',
    projectId: 'flutter-ecommerce-7407b',
    storageBucket: 'flutter-ecommerce-7407b.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8udR6zu0gCBtjGk95HE055sSCApktzRs',
    appId: '1:1001638282578:web:430b3aa6dfcf3a2e44268b',
    messagingSenderId: '1001638282578',
    projectId: 'flutter-ecommerce-7407b',
    authDomain: 'flutter-ecommerce-7407b.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-7407b.appspot.com',
    measurementId: 'G-1SZVM678G2',
  );
}
